### ISSUE TITLE
Make shell script macOS md5 aware

### ISSUE THREAD

**Issue by jb242** [nullobject/rygar-fpga#1]
Shell script expects Linux/GNU "md5sum" command and output, so will show failure when built on macOS despite good hash. Suggest adding awareness of BSD/macOS "md5" command.
===============
===============

23:08:36 rygar $ ./build-rom.sh
'########::'##:::'##::'######::::::'###::::'########::
 ##.... ##:. ##:'##::'##... ##::::'## ##::: ##.... ##:
 ##:::: ##::. ####::: ##:::..::::'##:. ##:: ##:::: ##:
 ########::::. ##:::: ##::'####:'##:::. ##: ########::
 ##.. ##:::::: ##:::: ##::: ##:: #########: ##.. ##:::
 ##::. ##::::: ##:::: ##::: ##:: ##.... ##: ##::. ##::
 ##:::. ##:::: ##::::. ######::: ##:::: ##: ##:::. ##:
..:::::..:::::..::::::......::::..:::::..::..:::::..::

Unzipping rygar.zip
Building a.rygar.rom
Checking MD5
./build-rom.sh: line 62: md5sum: command not found
WARNING: The MD5 for the target ROM is invalid. Please check your source ROM files.
Cleaning up /var/folders/g4/6psgdy8114b8lvzfkc1p823w0000gn/T/tmp.BDt44mET
23:08:46 rygar $
23:08:47 rygar $ md5 a.rygar.rom
MD5 (a.rygar.rom) = e0355e7803fdab0a8d8b5bda284ef2a5

**Comment by nullobject** [comment]
@jb242 Oops, I should have definitely used the system `md5` utility.

Thanks for the report, I will fix this ASAP ❤️

**Comment by nullobject** [comment]
This has been fixed.
