### ISSUE TITLE
Fails to boot, resulting in green or black screen

### ISSUE THREAD

**Issue by bitbarista** [nullobject/rygar-fpga#4]
Fails to boot, resulting in green or black screen. ROM compiled from mame 0.213 using both Windows batch file, Linux script and Linux cat command. Others have reported the same issue. Maybe memory related, does it support 64MB memory card?

**Comment by nullobject** [comment]
@bedfelllow There have been reports of people having issues with some RAM modules, so it's likely that your ROMs are fine and the issue lies with my SDRAM controller code.

Will investigate.

**Comment by mdmmarshall67** [comment]
I wonder if it's having problems with the sdram timing rather than the size of ram itself .I have 32 mb of sdram .I can get it to work if I reload the rom /core a few times .thanx for the work you put into this core

**Comment by nullobject** [comment]
@mdmmarshall67 Yes. From what I've seen it looks like a SDRAM timing issue.

**Comment by nullobject** [comment]
This will be fixed in the next beta release.

**Comment by nullobject** [comment]
This has been fixed in the latest beta.
